### PR TITLE
Earlier requests

### PR DESCRIPTION
**Pull request by jonathanrobie**
These corrections were requested by Joel and Randall about 8 weeks ago in a set of issues.  Issuing a pull request to allow them to be examined, modified, or committed more efficiently.

### CODE REVIEW

**Comment by jdejoode** [comment]
Thanks Jonathan, does this PR actually include the previous one? I've been reviewing the previous one, so once that's merged it, could this PR be transformed to only contain what was not covered in the previous one? Thoughts?

**Comment by jdejoode** [comment]
Would it be possible to provide references to the issues that are covered in this PR (and ditto in the other PR)? That would make it easier to close the issues after the merge.

**Comment by jdejoode** [comment]
Any update here @jonathanrobie? Thanks!

**Comment by thesmartwon** [comment]
I'd like to see these changes merged, so I'll answer some of the questions.

> Thanks Jonathan, does this PR actually include the previous one?

Yes. You can verify that the SHA (2408955) is the same.

> I've been reviewing the previous one, so once that's merged it, could this PR be transformed to only contain what was not covered in the previous one?

That will automatically happen.

> Would it be possible to provide references to the issues that are covered in this PR (and ditto in the other PR)?

Together these close #90 .

**Comment by jonathanrobie** [comment]
Yes, that is correct.

Jony

**Comment by jdejoode** [comment]
Thanks @thesmartwon and @jonathanrobie

**Pull request merged**
