### PR TITLE
MAPM: Fix chapter names

### PR DESCRIPTION
**Pull request by didib**
As is customary, replace the chapter names for chapters 15 and 16 to 'טו' and 'טז', respectively. See e.g.:

https://en.wikipedia.org/wiki/Significance_of_numbers_in_Judaism#15

### CODE REVIEW

**Comment by jag3773** [comment]
@DavidTroidl or @jdejoode any thoughts on this PR?

**Comment by oxidian24** [comment]
@DavidTroidl Hello David, Sorry that I write here but I do not know how to contact you. Are you still active in the google group OSHB https://groups.google.com/g/openscriptures-hb or can I ask you here? Where? May I use your data tags and verse structure (levels) and how to get them to be easy parsed? I would like to use it to create new App to compare bible verses using sentence structure comparison between hebrew and English translations.

**Review by jdejoode — APPROVED** [review]
Yes, this is a very good fix. The numbers at a verse level were fine, but those at the chapter level occasionally still used a letter combination that could imply a reference to the divine name. This PR fixes those errors.

I checked whether the corpus is consistent in its choice of the alternative (there are two, inverting the letters or doing a different addition such as 9+6 rather than 10 +5). I have not gone through all occurrence, but a quick find does suggest that this merge now makes the verse level and chapter level numbers consistent.

**Comment by jdejoode** [comment]
Thanks for your PR @didib 

Great work!

**Pull request merged**
